### ISSUE TITLE
Why is the sliding direction reversed?

### ISSUE THREAD

**Issue by Sjlver** [seanluong/15-puzzle#8]
I find this really confusing... have you tried the alternative of not reversing it?

You might also consider using WASD in a non-reversed way, and arrow-keys in a reversed way. Then players have both options.

I like the idea of the game!

**Comment by ghost** [comment]
Hi @Sjlver 
Thanks for your comment. The point is that the empty cell is like a hole and we are not controlling the hole but the tiles around the hole.

At first I was not in the reverse direction. Then I gave the game to some people to play on a moble device and their first impression was to move the adjacent tiles :(.

**Comment by ghost** [comment]
But the idea of having WASD is a really nice one. You can also try the game from the browser of a mobile devices and see if the reverse direction makes sense to you or not.

Thank you :D.

**Comment by ghost** [comment]
@Sjlver your WASD proposal is now implemented: http://xuanluong.github.io/15-puzzle/. Thanks, Jonas ;).
